from pathlib import Path

LEVEL_NAME = "test"
LEVEL_DURATION = 5.0
SONG_START = 0.0
START_POSITION = (0.0, 0.0)
START_DIRECTION = "DOWN_RIGHT"
START_SPEED = 500.0
DEFAULT_BPM = 120.0
LEVEL_END_BUFFER = 3.0
OBJECT_SPAWN_LEAD = 0.75
OUTPUT_DIRECTORY = Path(__file__).parent
PREDICT_TIME = 1